### ISSUE TITLE
libxdf doesn't build on Mac OS X

### ISSUE THREAD

**Issue by cbrnr** [Yida-Lin/libXDF#1]
I just tried to build libxdf on Mac OS X. With the current `XDF.pro` file it doesn't work and I had to add the following flags:

    QMAKE_LFLAGS += -stdlib=libc++
    QMAKE_CXXFLAGS=-std=gnu++11 -stdlib=libc++

However, even when these flags are added I get the following two errors:

    xdf.cpp:608:32: error: non-constant-expression cannot be narrowed from type 'typename
          iterator_traits<__wrap_iter<pair<int, int> *> >::difference_type' (aka 'long') to 'int' in
          initializer list [-Wc++11-narrowing]
                        int index {std::distance(srateMap.begin(),it)} ;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    xdf.cpp:608:32: note: insert an explicit cast to silence this issue
                        int index {std::distance(srateMap.begin(),it)} ;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   static_cast<int>(                 )
    xdf.cpp:615:20: error: non-constant-expression cannot be narrowed from type 'typename
          iterator_traits<__wrap_iter<pair<int, int> *> >::difference_type' (aka 'long') to 'int' in
          initializer list [-Wc++11-narrowing]
            int index {std::distance(srateMap.begin(),
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    xdf.cpp:615:20: note: insert an explicit cast to silence this issue
            int index {std::distance(srateMap.begin(),
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There are also some warnings, but let's try to fix the errors first :-).

**Comment by Yida-Lin** [comment]
@cbrnr Hmm weird. Does it work fine in Linux?

I don't have access to a Mac but I would suggest:

1. I used C++11 uniform initialization here. Maybe let's do it in a more conventional way, using assign = operator instead of uniform initialization {}.
2. If this doesn't help, let's try `static_cast<int>(whatever is inside)` to see whether the error persists

`int index = static_cast<int>(std::distance(srateMap.begin(),it)) ;`

`int index = static_cast<int>(std::distance(srateMap.begin(),it) ;`
           
etc.

**Comment by cbrnr** [comment]
You're right, the initialization seems to be a problem (although I don't know why because clang++ should support all C++11 features). I've replaced the curly braces with normal parentheses and the errors disappear.

However, I now get the following error:

    multi_stage.c:27:10: fatal error: 'malloc.h' file not found
    #include "malloc.h"

On Linux, using g++ works fine, but with clang++ I get the same initialization-related errors. So I think we should definitely change the code as I've mentioned before.

Also, I think we don't need to set any `CXXFLAGS` or `CFLAGS` in the .pro file. Adding `c++11` to the `CONFIG` variable should be sufficient.

**Comment by Yida-Lin** [comment]
@cbrnr Great to know the curly braces might cause some problems, I better stick with the more conventional way.

Hmm I am really out of ideas about the missing "malloc.h" file... I googled this issue and [here](http://earthworm.isti.com/trac/earthworm/ticket/141) seems to be a thread. Not sure whether it will work. Please keep me updated on this.

**Comment by cbrnr** [comment]
Yes, I'll keep trying to fix the problem on Mac OS X and let you know once I've resolved the issue.

**Comment by cbrnr** [comment]
I think the problem might be related to qmake. For whatever reason, my Qt 5 (installed via Homebrew) seems to insist in Xcode. I cannot select the Command Line Tools, which might fix this error.

Since libxdf doesn't require Qt at all, may I suggest that we switch from qmake to cmake?

**Comment by cbrnr** [comment]
OK, it's not `qmake` (but we should switch to `cmake` anyway). The problem is `smarc` using the deprecated header `malloc.h`. All functions defined there are available in `stdlib.h`. I've commented out all `#include "malloc.h"` lines in all `smarc`-related files and the build is working.

@Yida-Lin can you please test this if it builds on your machine? I'll create a PR where you will also find the `CMakeLists.txt` file required by `cmake`.
