### ISSUE TITLE
Add support to build shared lib

### ISSUE THREAD

**Issue by cbrnr** [Yida-Lin/libxdf#12]
Let's add an option to build libxdf as a shared lib, especially on Linux this is what people want (see e.g. [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860083)).

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens,

This is now done. Default is set to build both :)

**Comment by cbrnr** [comment]
We should also update cmake though.
