### ISSUE TITLE
Rename to libxdf

### ISSUE THREAD

**Issue by cbrnr** [Yida-Lin/libxdf#2]
I think it would be a good idea to rename the project to `libxdf` - this would make life on the command line a bit easier :-).

Similarly, the file `XDF.pro` could be renamed to `xdf.pro` or maybe even better to `libxdf.pro`.

**Comment by Yida-Lin** [comment]
@cbrnr :) I think my earlier attempt was made exactly as `libxdf.pro`, but then the `.a` file became the grotesque `liblibxdf.a` LOL. Or do you suggest to manually alter just the `pro` file from `xdf.pro` to `libxdf.pro`?

**Comment by cbrnr** [comment]
The latter - just rename the `.pro` file. The target defined in the .pro file should be `xdf` (I'd change it to small letters as well).

**Comment by Yida-Lin** [comment]
@cbrnr Will do

**Comment by Yida-Lin** [comment]
@cbrnr seems altering only the `.pro` file doesn't work. Qt Creator IDE doesn't allow me to alter the name inside it. If I alter it outside the IDE, it then cannot find the file anymore.

As an alternative I built another copy with all lower case, like `libxdf.a` etc. Currently they are in a different directory. I will update this one soon.

**Comment by cbrnr** [comment]
I'm not sure I understand you. I renamed the file to xdf.pro, changed the target to xdf, and everything worked. It might be a Windows-related problem, because Windows file systems usually doesn't differentiate between small and caps.

Anyway, since we're going to switch to cmake anyway, we won't need the .pro file at all. You can rename the project in the settings tab directly on the GitHub website.

**Comment by Yida-Lin** [comment]
@cbrnr Unfortunately I think I am having some trouble here. I tried doing it with CMake: we should add `set_property(TARGET xdf PROPERTY C_STANDARD 99)` otherwise there are some smarc code that doesn't compile. After doing so, it builds correctly.

Everything looks fine until I reached a point trying to open a mega-huge 600MB file; it crashed. Then I replaced it with a previous build made by qmake and it doesn't crash. Apparently there are some problems in this step. (I am very embarrassed to say I don't know CMake well. All I did is to add CMake in the Qt Toolkit and do everything in Qt Creator IDE. I am one of those amateurs who can't live without GUI...)

![2016-12-09 3](https://cloud.githubusercontent.com/assets/20526646/21063417/86cff404-be23-11e6-9e93-e3fbd272e290.png)

**Comment by cbrnr** [comment]
Can you post the error messages that you get without this flag?

Regarding the crash, the difference can only be due to different compiler flags. Can you post the compiler commands created by qmake and cmake?

**Comment by Yida-Lin** [comment]
@cbrnr @josef-faller

The error message is bad_alloc:

![2016-12-09 6](https://cloud.githubusercontent.com/assets/20526646/21064357/560bfd2c-be28-11e6-8f21-4c4754773bd6.png)

and below is my settings of cmake in Qt Creator: not sure whether anything is wrong with my setting.

![2016-12-09 4 _li](https://cloud.githubusercontent.com/assets/20526646/21064374/6245fa34-be28-11e6-9e94-c494a3a3b106.jpg)
![2016-12-09 5](https://cloud.githubusercontent.com/assets/20526646/21064378/65613f9e-be28-11e6-8206-ca0fad071d49.png)

**Comment by Yida-Lin** [comment]
@cbrnr 

Because of the crashing bug I have reset the master back to qmake, and created a new branch called "CMake" to work on the CMake version until we resolve the bug.

**Comment by Yida-Lin** [comment]
>Can you post the error messages that you get without this flag?
>Regarding the crash, the difference can only be due to different compiler flags. Can you post the compiler >commands created by qmake and cmake?

@cbrnr Sorry I don't really understand what compiler flags are. About the compiler commands, are you talking about these?

![2016-12-11](https://cloud.githubusercontent.com/assets/20526646/21078552/1a99d7d0-bf42-11e6-94b2-6adbeaa623d2.png)
![2016-12-11 1](https://cloud.githubusercontent.com/assets/20526646/21078553/1a9abc04-bf42-11e6-9a2c-fc5a40a7198f.png)

**Comment by Yida-Lin** [comment]
Fixed #2
