### ISSUE TITLE
Need to change the way libxdf finds min time stamp and max time stamp

### ISSUE THREAD

**Issue by Yida-Lin** [Yida-Lin/libxdf#8]
@cbrnr 

I found that in some streams the time stamps contains trash values, and the current approach that by looking for the first and last value in the time stamp vector as the min and max time stamps contains some risk.

For instance, in the following file, the last sample of the blue stream contains the max time stamp, but in the figure it actually doesn't end the last.

![image](https://cloud.githubusercontent.com/assets/20526646/24179245/6b95d576-0e84-11e7-844f-aa125f37b788.png)

**Comment by Yida-Lin** [comment]
@cbrnr On the right side is the vector of time stamps. As you can see, most of them are trash values except one (which I drew an arrow pointing to it). This means, time stamps are not reliable at all. They are not even sorted (like a set) so it's dangerous to look for only the last value as the max. 

We need to rethink the way to load and draw XDF signals in SigViewer

![2017-03-21 5 _li](https://cloud.githubusercontent.com/assets/20526646/24181344/ce2cf8ca-0e90-11e7-9e94-c551c635279d.jpg)

**Comment by cbrnr** [comment]
I'm not sure if this is even valid XDF. Time stamps are optional, but if they are present we should be able to assume that they are valid. So trash values as you call them are not allowed IMO. However, the order of sample chunks is not fixed, so it is possible that time stamps are not sorted (but a sane recording environment should never produce such files in the first place). @chkothe do you have any thought on this?

**Comment by Yida-Lin** [comment]
@cbrnr The file is located right [here](https://github.com/sccn/xdf/blob/master/xdf_sample.xdf).

**Comment by cbrnr** [comment]
What do you mean? This file opens fine and this was also part of our test files.

**Comment by Yida-Lin** [comment]
@cbrnr I mean the 44100Hz stream of this file contains trash values in time stamps

**Comment by cbrnr** [comment]
Ah I see. But SigViewer has no problems visualizing it, right? Or is there a problem related to these trash time stamps?

**Comment by Yida-Lin** [comment]
@cbrnr Seems the file should end where the blue stream stops (see figure above), but right now the blue stream ends earlier than the green stream. Or that because the green stream contains inaccurate time stamps, I failed to accurately calculate the length.

**Comment by cbrnr** [comment]
But this makes no sense. If there are time stamps they cannot be junk. That's why time stamps are optional. Are you absolutely sure you are parsing the samples chunk correctly?

**Comment by cbrnr** [comment]
I see that you deduce the time stamp if it isn't in the file. Can you check if this calculation is correct?

**Comment by Yida-Lin** [comment]
@cbrnr I think so, though right now I can't 100% prove I did it right, but since the irregular stream (blue) overall displays fine (events and irregular streams purely rely on time stamps) I assume it is correct.

However, there is a loophole in my current approach, that I calculate the total length of the file by searching the last value of each TS vector. This can be risky.

I will look into the deduction part to check.

**Comment by Yida-Lin** [comment]
@cbrnr Aha, I see why. Actually you pointed it out where it was wrong: it's the deduction part.

I added the sampling interval to the base of 0, but in most files the time stamp actually don't start from 0.

My fault sorry :)

**Comment by cbrnr** [comment]
You're welcome and thanks for double-checking :-)

**Comment by Yida-Lin** [comment]
@cbrnr Fixed in the newest commit

**Comment by cbrnr** [comment]
There doesn't seem to be a huge difference in the sample file - the mouse stream still stop before the audio stream. However, there seem to be missing values now toward the end of stream 0 (MouseY) which weren't there before (compare this screenshot with the one you posted at the top).
![screen shot 2017-03-23 at 09 00 14](https://cloud.githubusercontent.com/assets/4377312/24237578/232298dc-0fa7-11e7-91b7-72d0e82a1798.png)

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens, 

I think this problem already appear in the previous versions. I think it's visualization problem, because if you zoom in vertically those missing part will be painted. I suspect it may have things to do with `setClipRect`.

Another thing is currently I use float as time stamp, but I saw float only keeps the precision to 1 digit after the decimal point, which is insufficient for time stamps, could also be the reason why the blue stream ends early. I changed it to double but this file crashed in debug mode, because it has 170,000 time stamps and I think it failed to allocate.

**Comment by cbrnr** [comment]
I still think these trash time stamps are invalid. However, maybe we can work around that - is there a way to determine if a value is a valid time stamp or not? I saw that these invalid time stamps have tiny values, and they seem to be the identical. Maybe one way to check if a time stamp is invalid is to check its size; if it is too small we discard it. In addition, or alternatively, we could only keep unique time stamps since I don't think you can have two (or more) identical time stamp values in a stream.

**Comment by Yida-Lin** [comment]
@cbrnr Hi Clemens,

I think if you pull my newest commit, these trash stamps shouldn't be appearing anymore? 

1. Yes, maybe overtime I can add another condition flow, that if the time stamp is smaller than the beginning stamp, I discard it.
2. However, because currently time stamps are in the format of float, which only keeps one precision after the decimal point, there are lots of duplicates

**Comment by Yida-Lin** [comment]
Fixed.

**Comment by cbrnr** [comment]
Thanks @Yida-Lin. Just to clear things up, floats are not limited to one decimal place - [single precision floats have 6-9 significant decimals](https://en.wikipedia.org/wiki/Single-precision_floating-point_format). So the problem that most time stamps are identical are not likely due to the use of floats.
